permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "frozenxia"
email: "frozenxia@hotmail.com"
description: "Developer"
github_username:  "frozenxia"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "frozenxia"



url: "http://frozenxia.github.io"
imgrepo: "http://frozenxia.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"
#gems: [jekyll-paginate]

